### ISSUE TITLE
Documentation Out of Date for Submit Expense Report

### ISSUE THREAD

**Issue by OverlordRon** [SAP-docs/preview.developer.concur.com#1066]
The V1 Endpoint for Submitting an expense report does not work as described in the documentation.  I couldn't get it to work. 

However, if I re-work the V4 endpoint (e.g. https://{datacenterURI}/expensereports/v4/users/{userID}/context/{contextType}/reports/{reportId}/approve) and change "/approve" to "/submit" and add argument to the header "X-UserID" with the appropriate userName, then the api call works as intended.

**Comment by RoAnnC1** [comment]
@OverlordRon 
Hi,
Unfortunately the developer teams responsible for APIs don't monitor this GitHub repo. It would be best to reach out to your SAP Concur contact for this information.
