### ISSUE TITLE
Inconsistent Behavior in Report and Expense Comment Delete APIs

### ISSUE THREAD

**Issue by ak-jhalani** [SAP-docs/preview.developer.concur.com#1195]
**Description:**

We have observed an inconsistent behavior with the report-level and expense/receipt-level comments in the SAP Concur API, particularly when handling the deletion of comments after report submission. Below is a summary of the issue:

**Issue Summary:**

When a comment is created and a report is submitted, the comment becomes locked or uneditable, as expected. However, when a report manager adds a comment and then sends the report back to the user, the following behavior occurs:

1. The manager's comment is submitted and visible as the latest comment.
2. If the manager subsequently deletes their comment, the previously locked user comment now becomes `is_latest = true` and is deletable again.

This behavior causes issues where user comments, which should remain locked after submission, are unexpectedly unlocked and editable/deletable once a higher-level comment is deleted. This is not the expected behavior, as the previous user comment should remain locked even after the manager's comment is deleted.

**Expected Behavior:**

- Once a comment is locked after report submission, it should remain locked, regardless of any subsequent comments being deleted by a report manager.
- Deleting a higher-level comment (e.g., manager comment) should not change the lock status or `is_latest` flag of previously locked user comments.

**Steps to Reproduce:**

1. Submit a report with user comments.
2. Have a report manager add a comment to the report and return the report to the user.
3. The manager deletes their comment.
4. The user comment that was previously locked is now unlocked (`is_latest = true`) and can be deleted.

**Impact:**

This behavior leads to confusion in the comment history and could potentially allow for the deletion of important comments that were meant to remain part of the record.

We kindly request your assistance in resolving this inconsistency, ensuring that once comments are locked after submission, they remain locked regardless of any actions taken by other users.

Thank you.

---

**Comment by RoAnnC1** [comment]
@ak-jhalani 
Unfortunately the developer teams responsible for APIs don't monitor this GitHub repo. It would be best to reach out to your SAP Concur contact for this information.
