### ISSUE TITLE
Documentation for PUT and POST have the same payload.

### ISSUE THREAD

**Issue by abhidotnet** [SAP-docs/preview.developer.concur.com#325]
Hello Team,
In your documentation, you have the same payload for PUT & POST. I am able to do a post, but the put fails with the following message

<Error xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Message>Request ID is mandatory to the (PUT) Payment Request API</Message>
</Error>

If I pass the ID in the URL  ```/api/v3.0/invoice/PaymentRequest/{id}```  **it still fails with the same message.**

Is something missing in the documentation? I am posting the link where this documentation is **available.**
https://github.com/SAP-docs/preview.developer.concur.com/blob/ca4fea394c9513b97e74ca80ee9cbb6e61faa86b/src/api-reference/invoice/v3.payment-request.markdown

**Comment by RoAnnC1** [comment]
Hi,
Unfortunately the developer teams responsible for APIs don't monitor this GitHub repo. It would be best to reach out to your Concur contact for this information.
