### ISSUE TITLE
Table Formatting Error

### ISSUE THREAD

**Issue by davokr** [SAP-docs/preview.developer.concur.com#922]
The schema table for Travel User is not formatted correctly.

[preview.developer.concur.com](https://github.com/SAP-docs/preview.developer.concur.com/tree/main)/[src](https://github.com/SAP-docs/preview.developer.concur.com/tree/main/src)/[api-reference](https://github.com/SAP-docs/preview.developer.concur.com/tree/main/src/api-reference)/[user-provisioning](https://github.com/SAP-docs/preview.developer.concur.com/tree/main/src/api-reference/user-provisioning)
/v4.user-provisioning.md

![CleanShot 2024-01-04 at 11 31 56@2x](https://github.com/SAP-docs/preview.developer.concur.com/assets/37805835/da9f8ab7-b017-425b-95cc-a27222ad60f9)

**Comment by RoAnnC1** [comment]
Fixed, thanks.
