### ISSUE TITLE
Posting Document Details Required fields

### ISSUE THREAD

**Issue by jetzerb** [SAP-docs/preview.developer.concur.com#931]
In `src/api-reference/financial-integration/v4.financial-integration.markdown`, [Posting Document Details](https://github.com/SAP-docs/preview.developer.concur.com/blob/main/src/api-reference/financial-integration/v4.financial-integration.markdown#posting-documents-details) indicates that `systemMessages` is **Required** but the verbiage "if any" indicates that it's optional.  Also, the example request in the [SAP Developer Center](https://developer.concur.com/api-reference/financial-integration/v4.financial-integration.html#post-financial-transactions-confirmations-) doesn't include `systemMessages` for the document that was successfully posted.

Meanwhile, the `postingDocs` array does _not_ indicate that it's required, but if not provided the endpoint returns `FAILURE` with error message `Invalid input value [postingDocs (): may not be blank]`

![image](https://github.com/SAP-docs/preview.developer.concur.com/assets/36859020/383e98cf-851f-4b9a-89e0-da03ef30543f)

Clarification would be appreciated.

**Comment by RoAnnC1** [comment]
@jetzerb 
Hi,
Unfortunately the developer teams responsible for APIs don't monitor this GitHub repo. It would be best to reach out to your SAP Concur contact for this information.
